# mongodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.mongo.Name }}
spec:
  replicas: {{ .Values.database.mongo.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: {{ .Values.database.mongo.Name }}
          image: {{ .Values.database.mongo.image }}
          ports:
            - containerPort: {{ .Values.database.mongo.containerport }}
