apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.nodeapp.name }}
spec:
  replicas: {{ .Values.apps.nodeapp.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: {{ .Values.apps.nodeapp.name }} 
          image: {{ .Values.apps.nodeapp.repositorytag }} 
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: MONGODB_URI
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: SESSION_SECRET
          ports:
            - containerPort: {{ .Values.apps.nodeapp.containerport }}       
