apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: suribau/myproject_web:v1.22
          env:
            - name: SESSION_SECRET
              value: P5qVo45L/32hCnT+ojTL6HTEoJgKe7eK7i2ilayKtZY=
            - name: MONGODB_URI
              value: mongodb://3.87.15.90:27017/test
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30020

