apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: suribau/myproject_web:v1.22
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: MONGODB_URI
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: SESSION_SECRET
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30020
      
