kind: Deployment 
apiVersion: apps/v1
metadata:
  name: mongodep
spec:
  replicas: 1
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [uat]}
  template:
    metadata:
      name: mongopod
      labels:
        env: uat
    spec:
      containers:
        - name: mongocont
          image: nginx
          ports:
            - containerPort: 80
---    
kind: Service 
apiVersion: v1 
metadata:
  name: mongosvc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: uat
  type: NodePort


    
