kind: Service
apiVersion: v1
metadata:
  name: mysvc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    env: dev
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: mypo
      labels:
        env: dev
    spec:
      containers:
        - name: mycont
          image: suribau/project_web:v1.16
          ports:
            -  containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://54.147.248.27:27017/development
          imagePullPolicy: Always
