# mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.mongo.Name }}
spec:
  selector:
    app: mongodb
  ports:
    - protocol: {{ .Values.service.database.protocol }}
      port: {{ .Values.service.database.externalPort }}
      targetPort: {{ .Values.service.database.internalPort }}
